<?php

use Illuminate\Database\Seeder;

class SizesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$info = array(
			array('id' => 3, 'alternative_id' => 'XS', 'name' => 'XS','alternative_name'=>'','alternative_name2'=>'','order'=>1,'is_complement'=>0),
			array('id' => 4, 'alternative_id' => 'S', 'name' => 'S','alternative_name'=>'','alternative_name2'=>'','order'=>2,'is_complement'=>0),
			array('id' => 5, 'alternative_id' => 'M', 'name' => 'M','alternative_name'=>'','alternative_name2'=>'','order'=>3,'is_complement'=>0),
			array('id' => 6, 'alternative_id' => 'L', 'name' => 'L','alternative_name'=>'','alternative_name2'=>'','order'=>4,'is_complement'=>0),
			array('id' => 7, 'alternative_id' => 'XL', 'name' => 'XL','alternative_name'=>'','alternative_name2'=>'','order'=>5,'is_complement'=>0),
			array('id' => 8, 'alternative_id' => 'XXL', 'name' => 'XXL','alternative_name'=>'','alternative_name2'=>'','order'=>6,'is_complement'=>0),
			array('id' => 9, 'alternative_id' => '0', 'name' => '0','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 10, 'alternative_id' => '1', 'name' => '1','alternative_name'=>'','alternative_name2'=>'','order'=>1,'is_complement'=>0),
			array('id' => 11, 'alternative_id' => '2', 'name' => '2','alternative_name'=>'','alternative_name2'=>'','order'=>2,'is_complement'=>0),
			array('id' => 12, 'alternative_id' => '3', 'name' => '3','alternative_name'=>'','alternative_name2'=>'','order'=>3,'is_complement'=>0),
			array('id' => 13, 'alternative_id' => '4', 'name' => '4','alternative_name'=>'','alternative_name2'=>'','order'=>4,'is_complement'=>0),
			array('id' => 14, 'alternative_id' => '4,5', 'name' => '4,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 15, 'alternative_id' => '5', 'name' => '5','alternative_name'=>'','alternative_name2'=>'','order'=>5,'is_complement'=>0),
			array('id' => 16, 'alternative_id' => '5,5', 'name' => '5,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 17, 'alternative_id' => '6', 'name' => '6','alternative_name'=>'','alternative_name2'=>'','order'=>6,'is_complement'=>0),
			array('id' => 18, 'alternative_id' => '6,5', 'name' => '6,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 19, 'alternative_id' => '7', 'name' => '7','alternative_name'=>'','alternative_name2'=>'','order'=>7,'is_complement'=>0),
			array('id' => 20, 'alternative_id' => '7,5', 'name' => '7,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 21, 'alternative_id' => '8', 'name' => '8','alternative_name'=>'','alternative_name2'=>'','order'=>8,'is_complement'=>0),
			array('id' => 22, 'alternative_id' => '8,5', 'name' => '8,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 23, 'alternative_id' => '9', 'name' => '9','alternative_name'=>'','alternative_name2'=>'','order'=>9,'is_complement'=>0),
			array('id' => 24, 'alternative_id' => '9,5', 'name' => '9,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 25, 'alternative_id' => '10', 'name' => '10','alternative_name'=>'','alternative_name2'=>'','order'=>10,'is_complement'=>0),
			array('id' => 26, 'alternative_id' => '10,5', 'name' => '10,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 27, 'alternative_id' => '11', 'name' => '11','alternative_name'=>'','alternative_name2'=>'','order'=>11,'is_complement'=>0),
			array('id' => 28, 'alternative_id' => '11,5', 'name' => '11,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 29, 'alternative_id' => '12', 'name' => '12','alternative_name'=>'','alternative_name2'=>'','order'=>12,'is_complement'=>0),
			array('id' => 30, 'alternative_id' => '13', 'name' => '13','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 31, 'alternative_id' => '14', 'name' => '14','alternative_name'=>'','alternative_name2'=>'','order'=>14,'is_complement'=>0),
			array('id' => 32, 'alternative_id' => '14,5', 'name' => '14,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 33, 'alternative_id' => '15', 'name' => '15','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 34, 'alternative_id' => '15,5', 'name' => '15,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 35, 'alternative_id' => '16', 'name' => '16','alternative_name'=>'','alternative_name2'=>'','order'=>16,'is_complement'=>0),
			array('id' => 36, 'alternative_id' => '16,5', 'name' => '16,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 37, 'alternative_id' => '17', 'name' => '17','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 38, 'alternative_id' => '17,5', 'name' => '17,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 39, 'alternative_id' => '18', 'name' => '18','alternative_name'=>'','alternative_name2'=>'','order'=>18,'is_complement'=>0),
			array('id' => 40, 'alternative_id' => '18,5', 'name' => '18,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 41, 'alternative_id' => '20', 'name' => '20','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 42, 'alternative_id' => '22', 'name' => '22','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 43, 'alternative_id' => '24', 'name' => '24','alternative_name'=>'','alternative_name2'=>'','order'=>24,'is_complement'=>0),
			array('id' => 44, 'alternative_id' => '26', 'name' => '26','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 45, 'alternative_id' => '28', 'name' => '28','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 46, 'alternative_id' => '30', 'name' => '30','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 47, 'alternative_id' => '32', 'name' => '32','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 48, 'alternative_id' => '34', 'name' => '34','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 49, 'alternative_id' => '36', 'name' => '36','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 50, 'alternative_id' => '38', 'name' => '38','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 51, 'alternative_id' => '40', 'name' => '40','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 52, 'alternative_id' => '42', 'name' => '42','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 53, 'alternative_id' => '44', 'name' => '44','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 54, 'alternative_id' => 'VAR', 'name' => 'VARIAS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 55, 'alternative_id' => '29', 'name' => '29','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 56, 'alternative_id' => '31', 'name' => '31','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 57, 'alternative_id' => '33', 'name' => '33','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 58, 'alternative_id' => '37', 'name' => '37','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 59, 'alternative_id' => '39', 'name' => '39','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 60, 'alternative_id' => '43', 'name' => '43','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 61, 'alternative_id' => '46', 'name' => '46','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 62, 'alternative_id' => '19,5', 'name' => '19,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 63, 'alternative_id' => '20,5', 'name' => '20,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 64, 'alternative_id' => 'CH', 'name' => 'CH','alternative_name'=>'','alternative_name2'=>'','order'=>1,'is_complement'=>0),
			array('id' => 65, 'alternative_id' => 'GD', 'name' => 'G','alternative_name'=>'GD','alternative_name2'=>'GRANDE','order'=>4,'is_complement'=>0),
			array('id' => 66, 'alternative_id' => 'XG', 'name' => 'XG','alternative_name'=>'EG','alternative_name2'=>'EXTRA GRANDE','order'=>10,'is_complement'=>0),
			array('id' => 67, 'alternative_id' => '21CM', 'name' => '21CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 68, 'alternative_id' => '24CM', 'name' => '24CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 69, 'alternative_id' => '0/0', 'name' => '0/0','alternative_name'=>'','alternative_name2'=>'','order'=>2,'is_complement'=>0),
			array('id' => 70, 'alternative_id' => '0/3', 'name' => '0/3','alternative_name'=>'','alternative_name2'=>'','order'=>3,'is_complement'=>0),
			array('id' => 71, 'alternative_id' => '42524', 'name' => '42524','alternative_name'=>'','alternative_name2'=>'','order'=>4,'is_complement'=>0),
			array('id' => 72, 'alternative_id' => '42619', 'name' => '42619','alternative_name'=>'','alternative_name2'=>'','order'=>5,'is_complement'=>0),
			array('id' => 73, 'alternative_id' => '2T', 'name' => '2T','alternative_name'=>'','alternative_name2'=>'','order'=>80,'is_complement'=>0),
			array('id' => 74, 'alternative_id' => '3T', 'name' => '3T','alternative_name'=>'','alternative_name2'=>'','order'=>81,'is_complement'=>0),
			array('id' => 75, 'alternative_id' => '4T', 'name' => '4T','alternative_name'=>'','alternative_name2'=>'','order'=>82,'is_complement'=>0),
			array('id' => 76, 'alternative_id' => '5T', 'name' => '5T','alternative_name'=>'','alternative_name2'=>'','order'=>83,'is_complement'=>0),
			array('id' => 77, 'alternative_id' => '3XL', 'name' => '3XL','alternative_name'=>'','alternative_name2'=>'','order'=>7,'is_complement'=>0),
			array('id' => 78, 'alternative_id' => 'EEEG', 'name' => 'EEEG','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 79, 'alternative_id' => 'EEG', 'name' => 'EEG','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 80, 'alternative_id' => '4EG', 'name' => '4EG','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 81, 'alternative_id' => '5EG', 'name' => '5EG','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 82, 'alternative_id' => 'EG', 'name' => 'EG','alternative_name'=>'','alternative_name2'=>'','order'=>5,'is_complement'=>0),
			array('id' => 83, 'alternative_id' => 'LG', 'name' => 'LG','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 84, 'alternative_id' => 'MD', 'name' => 'MD','alternative_name'=>'','alternative_name2'=>'','order'=>3,'is_complement'=>0),
			array('id' => 85, 'alternative_id' => '4XL', 'name' => '4XL','alternative_name'=>'','alternative_name2'=>'','order'=>8,'is_complement'=>0),
			array('id' => 86, 'alternative_id' => 'SM', 'name' => 'SM','alternative_name'=>'SM','alternative_name2'=>'SM','order'=>0,'is_complement'=>0),
			array('id' => 87, 'alternative_id' => 'CH2', 'name' => 'CH 2-4','alternative_name'=>'','alternative_name2'=>'','order'=>2,'is_complement'=>0),
			array('id' => 88, 'alternative_id' => 'MD6', 'name' => 'MD 6-8','alternative_name'=>'','alternative_name2'=>'','order'=>3,'is_complement'=>0),
			array('id' => 89, 'alternative_id' => 'G10', 'name' => 'G 10-12','alternative_name'=>'','alternative_name2'=>'','order'=>5,'is_complement'=>0),
			array('id' => 90, 'alternative_id' => 'EG14', 'name' => 'EG 14-16','alternative_name'=>'','alternative_name2'=>'','order'=>6,'is_complement'=>0),
			array('id' => 91, 'alternative_id' => '42713', 'name' => '42713','alternative_name'=>'','alternative_name2'=>'','order'=>6,'is_complement'=>0),
			array('id' => 92, 'alternative_id' => '43435', 'name' => '43435','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 93, 'alternative_id' => '18/24', 'name' => '18/24','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 94, 'alternative_id' => 'XXS', 'name' => 'XXS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 95, 'alternative_id' => '24/36', 'name' => '24/36','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 100, 'alternative_id' => 'U', 'name' => 'UNI','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 101, 'alternative_id' => '42526', 'name' => '42526','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 102, 'alternative_id' => '42589', 'name' => '42589','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 103, 'alternative_id' => '42652', 'name' => '42652','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 104, 'alternative_id' => '42380', 'name' => '42380','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 105, 'alternative_id' => '42382', 'name' => '42382','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 106, 'alternative_id' => '42384', 'name' => '42384','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 107, 'alternative_id' => '7X', 'name' => '7X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 108, 'alternative_id' => '2XL', 'name' => '2XL','alternative_name'=>'','alternative_name2'=>'','order'=>6,'is_complement'=>0),
			array('id' => 109, 'alternative_id' => '1XL', 'name' => '1XL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 110, 'alternative_id' => '42715', 'name' => '42715','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 111, 'alternative_id' => '13-14', 'name' => '13-14','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 112, 'alternative_id' => '15/16', 'name' => '15/16','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 113, 'alternative_id' => '06M', 'name' => '06M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 114, 'alternative_id' => '12M', 'name' => '12M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 115, 'alternative_id' => '18M', 'name' => '18M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 116, 'alternative_id' => '24M', 'name' => '24M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 117, 'alternative_id' => '03M', 'name' => '03M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 118, 'alternative_id' => '09M', 'name' => '09M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 119, 'alternative_id' => '3M', 'name' => '3M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 120, 'alternative_id' => '6M', 'name' => '6M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 121, 'alternative_id' => '9M', 'name' => '9M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 122, 'alternative_id' => '6XL', 'name' => '6XL','alternative_name'=>'','alternative_name2'=>'','order'=>10,'is_complement'=>0),
			array('id' => 123, 'alternative_id' => 'NB', 'name' => 'NB','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 124, 'alternative_id' => '34/36', 'name' => '34/36','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 125, 'alternative_id' => '3,5', 'name' => '3,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 126, 'alternative_id' => '42463', 'name' => '42463','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 127, 'alternative_id' => '35', 'name' => '35','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 128, 'alternative_id' => '42710', 'name' => '42710','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 129, 'alternative_id' => '1T', 'name' => '1T','alternative_name'=>'','alternative_name2'=>'','order'=>1,'is_complement'=>0),
			array('id' => 130, 'alternative_id' => '130', 'name' => 'MDT','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 131, 'alternative_id' => '131', 'name' => 'LGT','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 132, 'alternative_id' => '132', 'name' => 'XLT','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 133, 'alternative_id' => '133', 'name' => 'XXLT','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 134, 'alternative_id' => '3XLT', 'name' => '3XLT','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 135, 'alternative_id' => '5XL', 'name' => '5XL','alternative_name'=>'','alternative_name2'=>'','order'=>9,'is_complement'=>0),
			array('id' => 136, 'alternative_id' => '30/32', 'name' => '30/32','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 137, 'alternative_id' => '38/40', 'name' => '38/40','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 138, 'alternative_id' => '0-3', 'name' => '0-3','alternative_name'=>'TALLAS BEBE ','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 139, 'alternative_id' => '42524', 'name' => '42524','alternative_name'=>'TALLAS BEBE','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 140, 'alternative_id' => '42619', 'name' => '42619','alternative_name'=>'TALLAS MESES BEBE','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 141, 'alternative_id' => '42713', 'name' => '42713','alternative_name'=>'TALLAS MESES BEBE','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 142, 'alternative_id' => '43435', 'name' => '43435','alternative_name'=>'TALLAS MESES BEBE','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 143, 'alternative_id' => '18-24', 'name' => '18-24','alternative_name'=>'TALLAS MESES BEBE','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 144, 'alternative_id' => '35/40', 'name' => '35/40','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 145, 'alternative_id' => '39/44', 'name' => '39/44','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 146, 'alternative_id' => 'UNICA', 'name' => 'UNICA','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 147, 'alternative_id' => '6', 'name' => '6','alternative_name'=>'','alternative_name2'=>'','order'=>6,'is_complement'=>0),
			array('id' => 148, 'alternative_id' => '8', 'name' => '8','alternative_name'=>'','alternative_name2'=>'','order'=>8,'is_complement'=>0),
			array('id' => 149, 'alternative_id' => '4', 'name' => '4','alternative_name'=>'','alternative_name2'=>'','order'=>4,'is_complement'=>0),
			array('id' => 150, 'alternative_id' => '', 'name' => '','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 151, 'alternative_id' => '6A9', 'name' => '6A9','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 152, 'alternative_id' => '9A12', 'name' => '9A12','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 153, 'alternative_id' => '12A18', 'name' => '12A18','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 154, 'alternative_id' => '18A24', 'name' => '18A24','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 155, 'alternative_id' => '12ME', 'name' => 'Waist/Cintura','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 156, 'alternative_id' => '36M ', 'name' => 'Waist/Cintura','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 157, 'alternative_id' => '00M ', 'name' => 'Chest/Pecho','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 158, 'alternative_id' => '0', 'name' => '0','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 159, 'alternative_id' => 'T0Ma3M', 'name' => 'T0Ma3M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 160, 'alternative_id' => '3Ma6M', 'name' => '3Ma6M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 161, 'alternative_id' => '6Ma9M', 'name' => '6Ma9M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 162, 'alternative_id' => '9Ma12M', 'name' => '9Ma12M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 163, 'alternative_id' => '12Ma18M', 'name' => '12Ma18M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 164, 'alternative_id' => 'T18Ma24M', 'name' => 'T18Ma24M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 165, 'alternative_id' => ' UNICA', 'name' => ' UNICA','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 166, 'alternative_id' => '0Ma3M', 'name' => '0Ma3M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 167, 'alternative_id' => '35/38', 'name' => '35/38','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 168, 'alternative_id' => '39/42', 'name' => '39/42','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 169, 'alternative_id' => '35/39', 'name' => '35/39','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 170, 'alternative_id' => 'TS', 'name' => 'TS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 171, 'alternative_id' => 'LX', 'name' => 'LX','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 172, 'alternative_id' => '42683', 'name' => '42683','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 174, 'alternative_id' => '10A12', 'name' => '10A12','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 176, 'alternative_id' => '14A16', 'name' => '14A16','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 177, 'alternative_id' => '4A6', 'name' => '4A6','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 178, 'alternative_id' => '6A8', 'name' => '6A8','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 179, 'alternative_id' => '8A10', 'name' => '8A10','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 180, 'alternative_id' => 'UNIC', 'name' => 'long hood/Largo capucha','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 181, 'alternative_id' => '21', 'name' => '21','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 182, 'alternative_id' => '19', 'name' => '19','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 183, 'alternative_id' => 'X', 'name' => 'X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 184, 'alternative_id' => '17/18', 'name' => '17/18','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 185, 'alternative_id' => '19/20', 'name' => '19/20','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 186, 'alternative_id' => '27', 'name' => '27','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 187, 'alternative_id' => 'SRT', 'name' => 'SURTIDO','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 188, 'alternative_id' => '28/35', 'name' => '28/35','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 189, 'alternative_id' => 'C1', 'name' => 'T02/1 - T04/2 - T06/3 - T08/2','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 190, 'alternative_id' => 'C2', 'name' => 'T04/2 - T06/4 - T08/3 - T10/1','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 191, 'alternative_id' => 'C3', 'name' => 'T04/2 - T06/4 - T08/4','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 192, 'alternative_id' => 'C4', 'name' => 'T06/1 - T08/2 - T10/2 - T12/2 - T14/1','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 193, 'alternative_id' => 'C5', 'name' => 'T08/1 - T10/1 - T12/2 - T14/2 - T16/1 - T18/1','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 194, 'alternative_id' => '0M-3M', 'name' => '0M-3M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 195, 'alternative_id' => '3M-6M', 'name' => '3M-6M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 196, 'alternative_id' => '6M-9M', 'name' => '6M-9M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 197, 'alternative_id' => '9M-12M', 'name' => '9M-12M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 198, 'alternative_id' => '12M-18M', 'name' => '12M-18M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 199, 'alternative_id' => '18M-24M', 'name' => '18M-24M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 200, 'alternative_id' => '32B', 'name' => '32B','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 201, 'alternative_id' => '34B', 'name' => '34B','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 202, 'alternative_id' => '36B', 'name' => '36B','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 203, 'alternative_id' => '38B', 'name' => '38B','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 204, 'alternative_id' => '32/S', 'name' => '32/S','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 205, 'alternative_id' => '34/M', 'name' => '34/M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 206, 'alternative_id' => '36/L', 'name' => '36/L','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 207, 'alternative_id' => '38/XL', 'name' => '38/XL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 208, 'alternative_id' => 'S-M', 'name' => 'S-M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 209, 'alternative_id' => 'L-XL', 'name' => 'L-XL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 210, 'alternative_id' => '42651', 'name' => '42651','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 211, 'alternative_id' => '42714', 'name' => '42714','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 212, 'alternative_id' => '41974', 'name' => '41974','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 213, 'alternative_id' => '14-16', 'name' => '14-16','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 214, 'alternative_id' => '42525', 'name' => '42525','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 215, 'alternative_id' => '42588', 'name' => '42588','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 216, 'alternative_id' => '41', 'name' => '41','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 217, 'alternative_id' => 'ML', 'name' => 'ML','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 218, 'alternative_id' => 'UNIC', 'name' => 'UNICA','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 219, 'alternative_id' => '0a3MESES', 'name' => '0a3MESES','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 220, 'alternative_id' => '3a6MESES', 'name' => '3a6MESES','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 221, 'alternative_id' => '6a9MESES', 'name' => '6a9MESES','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 222, 'alternative_id' => '9a12MESES', 'name' => '9a12MESES','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 223, 'alternative_id' => 'T12a18MESES', 'name' => 'T12a18MESES','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 224, 'alternative_id' => '18a24MESES', 'name' => '18a24MESES','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 225, 'alternative_id' => 'LXL', 'name' => 'LXL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 226, 'alternative_id' => '23', 'name' => '23','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 227, 'alternative_id' => '25', 'name' => '25','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 228, 'alternative_id' => '42496', 'name' => '42496','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 229, 'alternative_id' => '42497', 'name' => '42497','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 230, 'alternative_id' => '9', 'name' => '9','alternative_name'=>'','alternative_name2'=>'','order'=>9,'is_complement'=>0),
			array('id' => 231, 'alternative_id' => '7', 'name' => '7','alternative_name'=>'','alternative_name2'=>'','order'=>7,'is_complement'=>0),
			array('id' => 232, 'alternative_id' => '45', 'name' => '45','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 233, 'alternative_id' => '42463', 'name' => '42463','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 234, 'alternative_id' => '42526', 'name' => '42526','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 235, 'alternative_id' => '42528', 'name' => '42528','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 236, 'alternative_id' => '42652', 'name' => '42652','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 237, 'alternative_id' => '42715', 'name' => '42715','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 239, 'alternative_id' => '36,5', 'name' => '36,5','alternative_name'=>'36,5','alternative_name2'=>'36,5','order'=>0,'is_complement'=>0),
			array('id' => 240, 'alternative_id' => '37,5', 'name' => '37,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 241, 'alternative_id' => '38,5', 'name' => '38,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 242, 'alternative_id' => '40,5', 'name' => '40,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 243, 'alternative_id' => '5', 'name' => '5','alternative_name'=>'','alternative_name2'=>'','order'=>5,'is_complement'=>0),
			array('id' => 244, 'alternative_id' => '12,5', 'name' => '12,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 245, 'alternative_id' => '1,5', 'name' => '1,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 246, 'alternative_id' => '2,5', 'name' => '2,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 247, 'alternative_id' => '35,5', 'name' => '35,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 248, 'alternative_id' => '21/22', 'name' => '21/22','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 249, 'alternative_id' => '23/24', 'name' => '23/24','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 250, 'alternative_id' => '25/26', 'name' => '25/26','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 251, 'alternative_id' => 'XXXL', 'name' => 'XXXL','alternative_name'=>'','alternative_name2'=>'','order'=>7,'is_complement'=>0),
			array('id' => 252, 'alternative_id' => '50', 'name' => '50','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 253, 'alternative_id' => '60', 'name' => '60','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 254, 'alternative_id' => '70', 'name' => '70','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 255, 'alternative_id' => '38D', 'name' => '38D','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 256, 'alternative_id' => '40D', 'name' => '40D','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 257, 'alternative_id' => '42D', 'name' => '42D','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 258, 'alternative_id' => '44D', 'name' => '44D','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 259, 'alternative_id' => '46D', 'name' => '46D','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 260, 'alternative_id' => '36D', 'name' => '36D','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 261, 'alternative_id' => '34C', 'name' => '34C','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 262, 'alternative_id' => '36C', 'name' => '36C','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 263, 'alternative_id' => '38C', 'name' => '38C','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 264, 'alternative_id' => '264', 'name' => 'O/S','alternative_name'=>'O/S','alternative_name2'=>'O/S','order'=>0,'is_complement'=>0),
			array('id' => 265, 'alternative_id' => '265', 'name' => 'S/M','alternative_name'=>'S/M','alternative_name2'=>'S/M','order'=>0,'is_complement'=>0),
			array('id' => 266, 'alternative_id' => '266', 'name' => 'M/L','alternative_name'=>'M/L','alternative_name2'=>'M/L','order'=>0,'is_complement'=>0),
			array('id' => 267, 'alternative_id' => '30/31', 'name' => '30/31','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 268, 'alternative_id' => '32/33', 'name' => '32/33','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 269, 'alternative_id' => '34/35', 'name' => '34/35','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 270, 'alternative_id' => '41/42', 'name' => '41/42','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 271, 'alternative_id' => '43/44', 'name' => '43/44','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 272, 'alternative_id' => '45/46', 'name' => '45/46','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 273, 'alternative_id' => '42,5', 'name' => '42,5','alternative_name'=>'42,5','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 274, 'alternative_id' => '44,5', 'name' => '44,5','alternative_name'=>'44,5','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 275, 'alternative_id' => '1X', 'name' => '1X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 276, 'alternative_id' => '2X', 'name' => '2X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 277, 'alternative_id' => '3X', 'name' => '3X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 278, 'alternative_id' => '4X', 'name' => '4X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 279, 'alternative_id' => 'RR', 'name' => 'SEGUNDAS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 280, 'alternative_id' => 'SO', 'name' => 'SOBRANTES','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 281, 'alternative_id' => '42462', 'name' => '42462','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 282, 'alternative_id' => '6', 'name' => '6','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 283, 'alternative_id' => '8', 'name' => '8','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 284, 'alternative_id' => '0a3', 'name' => '0a3','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 285, 'alternative_id' => '3a6', 'name' => '3a6','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 286, 'alternative_id' => 'TALLA UNICA', 'name' => 'TALLA UNICA','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 287, 'alternative_id' => '28-30', 'name' => '28-30','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 288, 'alternative_id' => '32-34', 'name' => '32-34','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 289, 'alternative_id' => '36-38', 'name' => '36-38','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 290, 'alternative_id' => '40-42', 'name' => '40-42','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 291, 'alternative_id' => '0', 'name' => '0','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 292, 'alternative_id' => '13,5', 'name' => '13,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 293, 'alternative_id' => '34-35', 'name' => '34-35','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 294, 'alternative_id' => '38-39', 'name' => '38-39','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 296, 'alternative_id' => '130515', 'name' => '130515','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 297, 'alternative_id' => '130615', 'name' => '130615','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 298, 'alternative_id' => '130715', 'name' => '130715','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 299, 'alternative_id' => '0', 'name' => '0','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 300, 'alternative_id' => 'S/M', 'name' => 'S/M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 301, 'alternative_id' => 'M/L', 'name' => 'M/L','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 302, 'alternative_id' => '0', 'name' => '0','alternative_name'=>'0','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 303, 'alternative_id' => '0', 'name' => '0','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 304, 'alternative_id' => '53', 'name' => '53','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 305, 'alternative_id' => '0', 'name' => '0','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 306, 'alternative_id' => '306', 'name' => 'AS','alternative_name'=>'AS','alternative_name2'=>'AS','order'=>1,'is_complement'=>0),
			array('id' => 307, 'alternative_id' => '307', 'name' => 'AM','alternative_name'=>'AM','alternative_name2'=>'AM','order'=>2,'is_complement'=>0),
			array('id' => 308, 'alternative_id' => '308', 'name' => 'AL','alternative_name'=>'AL','alternative_name2'=>'AL','order'=>3,'is_complement'=>0),
			array('id' => 309, 'alternative_id' => '309', 'name' => 'AXL','alternative_name'=>'AXL','alternative_name2'=>'AXL','order'=>4,'is_complement'=>0),
			array('id' => 310, 'alternative_id' => '310', 'name' => 'A2XL','alternative_name'=>'A2XL','alternative_name2'=>'A2XL','order'=>5,'is_complement'=>0),
			array('id' => 311, 'alternative_id' => '311', 'name' => 'A3XL','alternative_name'=>'A3XL','alternative_name2'=>'A3XL','order'=>6,'is_complement'=>0),
			array('id' => 312, 'alternative_id' => '312', 'name' => 'A4XL','alternative_name'=>'A4XL','alternative_name2'=>'A4XL','order'=>6,'is_complement'=>0),
			array('id' => 313, 'alternative_id' => '28/30', 'name' => '28/30','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 314, 'alternative_id' => '32/34', 'name' => '32/34','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 315, 'alternative_id' => '36/38', 'name' => '36/38','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 316, 'alternative_id' => '40/42', 'name' => '40/42','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 317, 'alternative_id' => '34,5', 'name' => '34,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 318, 'alternative_id' => '0/2', 'name' => '0/2','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 319, 'alternative_id' => '10M', 'name' => '10M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 320, 'alternative_id' => '12-L', 'name' => '12-L','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 321, 'alternative_id' => '14-XL', 'name' => '14-XL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 322, 'alternative_id' => 'XL/XXL', 'name' => 'XL/XXL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 323, 'alternative_id' => '49 CM', 'name' => '49 CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 324, 'alternative_id' => '59 CM', 'name' => '59 CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 325, 'alternative_id' => '69 CM', 'name' => '69 CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 326, 'alternative_id' => '48 CM', 'name' => '48 CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 327, 'alternative_id' => '58 CM', 'name' => '58 CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 328, 'alternative_id' => '68 CM', 'name' => '68 CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 329, 'alternative_id' => '60 CM', 'name' => '60 CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 330, 'alternative_id' => '71 CM', 'name' => '71 CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 331, 'alternative_id' => '24P', 'name' => '24 PULGADAS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 332, 'alternative_id' => '20P', 'name' => '20 PULGADAS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 333, 'alternative_id' => '28P', 'name' => '28 PULGADAS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 334, 'alternative_id' => '32C', 'name' => '32C','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 335, 'alternative_id' => '40C', 'name' => '40C','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 336, 'alternative_id' => 'L/XL', 'name' => 'L/XL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 337, 'alternative_id' => '39,5', 'name' => '39,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 338, 'alternative_id' => '43,5', 'name' => '43,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 339, 'alternative_id' => 'XS', 'name' => 'XS','alternative_name'=>'','alternative_name2'=>'','order'=>1,'is_complement'=>0),
			array('id' => 340, 'alternative_id' => 'S - 4-6', 'name' => 'S - 4/6','alternative_name'=>'','alternative_name2'=>'','order'=>2,'is_complement'=>0),
			array('id' => 341, 'alternative_id' => 'M 8-10', 'name' => 'M - 8/10','alternative_name'=>'','alternative_name2'=>'','order'=>3,'is_complement'=>0),
			array('id' => 342, 'alternative_id' => '41974', 'name' => 'L - 12/14','alternative_name'=>'','alternative_name2'=>'','order'=>4,'is_complement'=>0),
			array('id' => 343, 'alternative_id' => 'XL - 16', 'name' => 'XL - 16','alternative_name'=>'','alternative_name2'=>'','order'=>5,'is_complement'=>0),
			array('id' => 344, 'alternative_id' => '18', 'name' => '18','alternative_name'=>'','alternative_name2'=>'','order'=>18,'is_complement'=>0),
			array('id' => 345, 'alternative_id' => '48', 'name' => '48','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 346, 'alternative_id' => '58', 'name' => '58','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 347, 'alternative_id' => '68', 'name' => '68','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 348, 'alternative_id' => 'N006', 'name' => 'N006','alternative_name'=>'N006','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 349, 'alternative_id' => 'T2', 'name' => '2','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 350, 'alternative_id' => 'T3', 'name' => '3','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 351, 'alternative_id' => 'T4', 'name' => '4','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 352, 'alternative_id' => 'TM', 'name' => 'M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 353, 'alternative_id' => 'TL', 'name' => 'L','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 354, 'alternative_id' => 'TXL', 'name' => 'XL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 355, 'alternative_id' => 'TXXL', 'name' => 'XXL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 356, 'alternative_id' => 'TXS', 'name' => 'XS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 357, 'alternative_id' => 'T06', 'name' => '6','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 358, 'alternative_id' => 'T08', 'name' => '8','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 359, 'alternative_id' => 'T10', 'name' => 'T10','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 360, 'alternative_id' => 'T12', 'name' => 'T12','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 361, 'alternative_id' => 'T14', 'name' => 'T14','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 362, 'alternative_id' => 'T16', 'name' => 'T16','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 363, 'alternative_id' => 'TUNICA', 'name' => 'TUNICA','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 364, 'alternative_id' => 'T6', 'name' => 'T6','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 365, 'alternative_id' => 'T8', 'name' => 'T8','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 366, 'alternative_id' => 'T9', 'name' => 'T9','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 367, 'alternative_id' => 'T18', 'name' => 'T18','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 368, 'alternative_id' => 'T2T', 'name' => 'T2T','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 369, 'alternative_id' => 'T3T', 'name' => 'T3T','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 370, 'alternative_id' => 'T4T', 'name' => 'T4T','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 371, 'alternative_id' => 'T0', 'name' => 'T0','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 372, 'alternative_id' => 'T28', 'name' => 'T28','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 373, 'alternative_id' => 'T30', 'name' => 'T30','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 374, 'alternative_id' => 'T32', 'name' => 'T32','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 375, 'alternative_id' => 'T33', 'name' => 'T33','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 376, 'alternative_id' => 'T34', 'name' => 'T34','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 377, 'alternative_id' => 'T35', 'name' => 'T35','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 378, 'alternative_id' => 'T36', 'name' => 'T36','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 379, 'alternative_id' => 'T38', 'name' => 'T38','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 380, 'alternative_id' => 'T31', 'name' => 'T31','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 381, 'alternative_id' => '6X', 'name' => '6X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 382, 'alternative_id' => '6T', 'name' => '6T','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 383, 'alternative_id' => '8T', 'name' => '8T','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 384, 'alternative_id' => '42401', 'name' => '42401','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 385, 'alternative_id' => '42683', 'name' => '42683','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 386, 'alternative_id' => '20X3.5CM', 'name' => '20X3.5CM','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 387, 'alternative_id' => '20X20X3CMS', 'name' => '20X20X3CMS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 388, 'alternative_id' => '28X17X3CMS', 'name' => '28X17X3CMS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 389, 'alternative_id' => '22X23X3CMS', 'name' => '22X23X3CMS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 390, 'alternative_id' => '20.5X11.5X7CMS', 'name' => '20.5X11.5X7CMS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 391, 'alternative_id' => '20X3.5CMS', 'name' => '20X3.5CMS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 392, 'alternative_id' => '23X3CMS', 'name' => '23X3CMS','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 393, 'alternative_id' => '42486', 'name' => '42486','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 394, 'alternative_id' => '42548', 'name' => '42548','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 395, 'alternative_id' => '42610', 'name' => '42610','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 396, 'alternative_id' => '42672', 'name' => '42672','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 397, 'alternative_id' => '42734', 'name' => '42734','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 398, 'alternative_id' => '31/14', 'name' => '31/14','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 399, 'alternative_id' => '32/16', 'name' => '32/16','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 400, 'alternative_id' => 'MDI', 'name' => 'MEDIANA','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 401, 'alternative_id' => 'PQ', 'name' => 'PEQUEÃ‘A','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 402, 'alternative_id' => 'GR', 'name' => 'GRANDE','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 403, 'alternative_id' => '72', 'name' => '72','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 404, 'alternative_id' => '55', 'name' => '55','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 405, 'alternative_id' => '61', 'name' => '61','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 406, 'alternative_id' => '56', 'name' => '56','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 407, 'alternative_id' => '51', 'name' => '51','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 408, 'alternative_id' => '90', 'name' => '90','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 409, 'alternative_id' => '75', 'name' => '75','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 410, 'alternative_id' => '47', 'name' => '47','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 411, 'alternative_id' => '82', 'name' => '82','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 412, 'alternative_id' => 'T1', 'name' => 'T1','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 413, 'alternative_id' => 'T7', 'name' => 'T7','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 414, 'alternative_id' => 'T5', 'name' => 'T5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 415, 'alternative_id' => 'T11', 'name' => 'T11','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 416, 'alternative_id' => 'T13', 'name' => 'T13','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 417, 'alternative_id' => 'T25', 'name' => 'T25','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 418, 'alternative_id' => 'T26', 'name' => 'T26','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 419, 'alternative_id' => 'T27', 'name' => 'T27','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 420, 'alternative_id' => 'T29', 'name' => 'T29','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 421, 'alternative_id' => '13/14', 'name' => '13/14','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 422, 'alternative_id' => 'SM/LXL', 'name' => 'SM/LXL','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 423, 'alternative_id' => '423', 'name' => 'YM','alternative_name'=>'YM','alternative_name2'=>'YM','order'=>0,'is_complement'=>0),
			array('id' => 424, 'alternative_id' => '424', 'name' => 'YL','alternative_name'=>'YL','alternative_name2'=>'YL','order'=>0,'is_complement'=>0),
			array('id' => 425, 'alternative_id' => '63', 'name' => '63','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 426, 'alternative_id' => 'T6 9', 'name' => 'T6 9','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 427, 'alternative_id' => 'T9 12', 'name' => 'T9 12','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 428, 'alternative_id' => 'T12 18', 'name' => 'T12 18','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 429, 'alternative_id' => 'T18 24', 'name' => 'T18 24','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 430, 'alternative_id' => 'T0 3', 'name' => 'T0 3','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 431, 'alternative_id' => 'T3 6', 'name' => '42524','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 432, 'alternative_id' => '42589', 'name' => '42589','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 433, 'alternative_id' => '15-16', 'name' => '15-16','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 434, 'alternative_id' => '67', 'name' => '67','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 435, 'alternative_id' => '64', 'name' => '64','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 436, 'alternative_id' => '71', 'name' => '71','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 437, 'alternative_id' => '42525', 'name' => '42525','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 438, 'alternative_id' => '42651', 'name' => '42651','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 439, 'alternative_id' => '1X/2X', 'name' => '1X/2X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 440, 'alternative_id' => '3X/4X', 'name' => '3X/4X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 441, 'alternative_id' => '12Y', 'name' => '12Y','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 442, 'alternative_id' => '14Y', 'name' => '14Y','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 443, 'alternative_id' => '16Y', 'name' => '16Y','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 444, 'alternative_id' => '65', 'name' => '65','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 445, 'alternative_id' => '76', 'name' => '76','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 446, 'alternative_id' => '0M', 'name' => '0M','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 447, 'alternative_id' => '8X', 'name' => '8X','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 448, 'alternative_id' => 'XS-S', 'name' => 'XS-S','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 449, 'alternative_id' => 'M-L', 'name' => 'M-L','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 450, 'alternative_id' => '80x150cm', 'name' => '80x150cm','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 451, 'alternative_id' => '120x170cm', 'name' => '120x170cm','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 452, 'alternative_id' => '160x230cm', 'name' => '160x230cm','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 453, 'alternative_id' => '40B', 'name' => '40B','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 454, 'alternative_id' => '32A', 'name' => '32A','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 455, 'alternative_id' => 'BUSO                ', 'name' => '880/464','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 456, 'alternative_id' => 'CHAQUETA TELAS VARIA', 'name' => '640/546','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 457, 'alternative_id' => 'CHAQUETA TELAS VARIA', 'name' => '640/586','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 458, 'alternative_id' => 'SWETER CUSTER BLACK ', 'name' => '448/348','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 459, 'alternative_id' => 'CHAQUETA TELAS VARIA', 'name' => '992/563','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 460, 'alternative_id' => 'CHAQUETA TELAS VARIA', 'name' => '992/529','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 461, 'alternative_id' => 'CHAQUETA DEPORTIVA  ', 'name' => '1392/394','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 462, 'alternative_id' => 'CHAQUETA            ', 'name' => '1392/361','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 463, 'alternative_id' => 'BUSO DAMA           ', 'name' => '1392/362','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 464, 'alternative_id' => 'CAMIBUSO            ', 'name' => '0/145','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 465, 'alternative_id' => 'CAMISETA CON CUELLO ', 'name' => '1176/185','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 466, 'alternative_id' => 'P/LON SUDADERA TEJ. ', 'name' => '912/450','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 467, 'alternative_id' => 'P/LON SUDADERA TEJ. ', 'name' => '912/407','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 468, 'alternative_id' => 'P/LON SUDADERA TEJ. ', 'name' => '912/234','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 469, 'alternative_id' => 'P/NETA LARGA PUNTO  ', 'name' => '840/267','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 470, 'alternative_id' => 'DOBLE', 'name' => 'DOBLE','alternative_name'=>'DOBLE','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 471, 'alternative_id' => '23,5', 'name' => '23,5','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			array('id' => 472, 'alternative_id' => 'FAL', 'name' => 'FALTANTE','alternative_name'=>'','alternative_name2'=>'','order'=>0,'is_complement'=>0),
			// Complement
			array('id' => 473, 'alternative_id' => 'A', 'name' => 'A','alternative_name'=>'A','alternative_name2'=>'A','order'=>0,'is_complement'=>1),
			array('id' => 474,'alternative_id' => 'B', 'name' => 'B','alternative_name'=>'B','alternative_name2'=>'B','order'=>0,'is_complement'=>'1'),
			array('id' => 475,'alternative_id' => 'C', 'name' => 'C','alternative_name'=>'C','alternative_name2'=>'C','order'=>0,'is_complement'=>'1'),
      	);
        //Delete the info table
        DB::table('wms_sizes')->delete();

        //Insert the data
        DB::table('wms_sizes')->insert($info);
    }
}
